BioArchLinux/Packages

BioArchLinux/r-pzfx/PKGBUILD, BioArchLinux/r-pzfx/lilac.py, BioArchLinux/r-pzfx/lilac.yaml
- r-pzfx
Close #
- [X ] Provide New Package
=> pzfx package: read GraphpadPrism data in R

BioArchLinux/r-modules/PKGBUILD, BioArchLinux/r-modules/lilac.py, BioArchLinux/r-modules/lilac.yaml, BioArchLinux/r-party/PKGBUILD, BioArchLinux/r-party/lilac.py, BioArchLinux/r-party/lilac.yaml, BioArchLinux/r-rvg/PKGBUILD, BioArchLinux/r-rvg/lilac.py, BioArchLinux/r-rvg/lilac.yaml
r-modules, r-party, r-rvg
Close #
They will be needed by some modules of  jasp-desktop.
=> add r-modules, r-party, r-rvg

BioArchLinux/megahit/PKGBUILD, BioArchLinux/megahit/lilac.py, BioArchLinux/megahit/lilac.yaml
=> add megahit PKGBUILD

BioArchLinux/spades/PKGBUILD, BioArchLinux/spades/lilac.py, BioArchLinux/spades/lilac.yaml, BioArchLinux/spades/spades
=> Add spades

BioArchLinux/spades/PKGBUILD, BioArchLinux/spades/spades
=> spades: build with cmake

BioArchLinux/subread/PKGBUILD, BioArchLinux/subread/lilac.yaml
=> Subread: Adding inital version of PKGBUILD and lilac.yaml

BioArchLinux/agat/PKGBUILD, BioArchLinux/agat/lilac.yaml
=> Adding PKGBUILD for agat

BioArchLinux/cutadapt/PKGBUILD, BioArchLinux/cutadapt/lilac.yaml, BioArchLinux/python-dnaio/PKGBUILD, BioArchLinux/python-dnaio/lilac.yaml, BioArchLinux/python-isal/PKGBUILD, BioArchLinux/python-isal/lilac.yaml, BioArchLinux/python-xopen/PKGBUILD, BioArchLinux/python-xopen/lilac.yaml
- cutadapt
- python-xopen
- python-dnaio
- python-isal
Close #108
=> Adding cutadapt and dependencies

BioArchLinux/mutmap/PKGBUILD, BioArchLinux/mutmap/lilac.yaml, BioArchLinux/qtl-seq/PKGBUILD, BioArchLinux/qtl-seq/lilac.yaml
=> Add mutmap & qtl-seq: tools for bulk segregant analysis

BioArchLinux/sra-tools/PKGBUILD, BioArchLinux/sra-tools/lilac.yaml
=> PKGBUILD for NCBI sra-tools 3.0.2

BioArchLinux/vcfanno/PKGBUILD, BioArchLinux/vcfanno/lilac.yaml
- vcfanno : annotate a VCF with other VCFs/BEDs/tabixed files
=> vcfanno: version 0.3.5

BioArchLinux/ad2vcf/PKGBUILD, BioArchLinux/ad2vcf/lilac.yaml, BioArchLinux/biolibc/PKGBUILD, BioArchLinux/biolibc/lilac.yaml, BioArchLinux/libxtend/PKGBUILD, BioArchLinux/libxtend/lilac.yaml
- ad2vcf
https://github.com/BioArchLinux/Packages/projects/3#card-80745536
=> add ad2vcf and dependencies

BioArchLinux/rnalysis/PKGBUILD, BioArchLinux/rnalysis/lilac.yaml
=> rnalysis: PKGBUILD version 3.4.2

tbtools/PKGBUILD, tbtools/lilac.yaml, tbtools/tbtools.desktop, tbtools/tbtools.sh
TBtools : GUI/CommandLine Tool Box for biologistists to utilize NGS data.
I modify the aur source from https://aur.archlinux.org/packages/tbtools
Close #
=> add TBtools

BioArchLinux/veusz/PKGBUILD, BioArchLinux/veusz/lilac.yaml
veusz is a SCI-plot software compare to origin
Close #
=> veusz: fork veusz from AUR

BioArchLinux/kaks_calculator/PKGBUILD, BioArchLinux/kaks_calculator/lilac.yaml
calculating selective pressure on coding and none-coding sequences
Close #
=> add kaks_calculator

BioArchLinux/r-fs/PKGBUILD, BioArchLinux/r-fs/lilac.py, BioArchLinux/r-fs/lilac.yaml, lilac-extensions/lilac_r_utils.py
Use the checks with `r-fs` package as an example.
=> Implement metadata checks for R packages

BioArchLinux/glimmerhmm/PKGBUILD, BioArchLinux/glimmerhmm/lilac.yaml
glimmerhmm is a new gene finder based on a Generalized Hidden Markov Model (GHMM).
Close #
=> glimmerhmm: add glimmerhmm

glimmerhmm/PKGBUILD, glimmerhmm/lilac.yaml
=> glimmerhmm: add glimmeerhmm

BioArchLinux/python-biotite/PKGBUILD, BioArchLinux/python-biotite/lilac.yaml, BioArchLinux/python-mizani/PKGBUILD, BioArchLinux/python-mizani/lilac.yaml, BioArchLinux/python-plotnine/PKGBUILD, BioArchLinux/python-plotnine/lilac.yaml
- python-plotnine
- python-biotite
- python-mizani
N.A.
plotnine is ggplot2 in python!!!
=> plotnine: Add plotnine and it's Dependencies

BioArchLinux/python-biosequences/PKGBUILD, BioArchLinux/python-biosequences/lilac.yaml, BioArchLinux/python-biotite/PKGBUILD, BioArchLinux/python-biotite/lilac.yaml, BioArchLinux/python-mizani/PKGBUILD, BioArchLinux/python-plotnine/PKGBUILD
- python-biosequences
- python-plotnine
- python-mizani
- python-biotite
python-biosequences: Add python-biosequences
python-biotite: Fix typo
python-plotnine: Polish PKGBUILD
python-mizani: Polish PKGBUILD
python-biotite: Polish PKGBUILD
=> python-*: Add python-biosequences, Fix python-biotite typo and Polish others

BioArchLinux/seqan3/PKGBUILD
- seqan3
the modified PKGBUILD builds seqan3 from sources by following build instructions from upstream.
=> seqan3: build from source tarball

BioArchLinux/ugene/PKGBUILD
the patch (https://github.com/ugeneunipro/ugene/pull/1270) already meraged
- ugene
fix PKGBUILD
the patch1270 merged, so remove from the source, so that can build
https://github.com/ugeneunipro/ugene/pull/1270
=> ugene: fix PKGBUILD

BioArchLinux/tcoffee/PKGBUILD, BioArchLinux/tcoffee/lilac.yaml
=> tcoffee: Add new pkg

BioArchLinux/tbtools/PKGBUILD
=> tbtools: update epoch

BioArchLinux/tcoffee/PKGBUILD
=> tcoffee: fix PKGBUILD

BioArchLinux/rstudio-desktop/PKGBUILD, BioArchLinux/rstudio-desktop/lilac.yaml, BioArchLinux/rstudio-desktop/pandoc_version.patch, BioArchLinux/rstudio-desktop/qt.conf, BioArchLinux/soci/PKGBUILD, BioArchLinux/soci/lilac.yaml
- rstudio-desktop
- soci (dependency for rstudio-desktop)
N. A.
i have tried to keep PKGBUILD, especially build functions, as close to the AUR version
=> Add rstudio-desktop to repo 

BioArchLinux/veusz/PKGBUILD, BioArchLinux/veusz/lilac.yaml
- veusz
fixed update from regex to use_max_tag
=> veusz: fix update

BioArchLinux/igv/PKGBUILD, BioArchLinux/igv/lilac.yaml
=> igv: Add package

BioArchLinux/veusz/lilac.yaml
=> veusz: alias to python

BioArchLinux/python-biotite/PKGBUILD
=> python-biotitle: add depend

BioArchLinux/imagej2/PKGBUILD, BioArchLinux/imagej2/lilac.yaml
- imagej2
Add new package
Close #
=> imagej2: Add package

BioArchLinux/kaks_calculator/lilac.yaml
- kaks_calculator
add AUR support
Close #
=> kaks_calculator: add AUR support

Documentation/adding packages.md, README.md
- NA
Close NA
adding documentation for submitting packages to repo. treat this as a draft documentation which can be later expanded upon as needed
=> *: Documentation for adding packages to repo 

BioArchLinux/r-jaspfrequencies/lilac.yaml
=> jaspfrequencies: add r depends

BioArchLinux/r-jasplearnstats/PKGBUILD, BioArchLinux/r-jasplearnstats/lilac.yaml
=> r-jasplearnstats: fix pkg dependencies

BioArchLinux/r-dfoptim/PKGBUILD, BioArchLinux/r-dfoptim/lilac.py, BioArchLinux/r-dfoptim/lilac.yaml, BioArchLinux/r-jaspmetaanalysis/PKGBUILD, BioArchLinux/r-jaspmetaanalysis/lilac.yaml
=> r-jaspmetaanalysis: add pkg depends

BioArchLinux/r-ggsurvfit/PKGBUILD, BioArchLinux/r-ggsurvfit/lilac.py, BioArchLinux/r-ggsurvfit/lilac.yaml, BioArchLinux/r-jaspsurvival/PKGBUILD, BioArchLinux/r-jaspsurvival/lilac.yaml
=> r-jaspsurvival: fix dependencies

BioArchLinux/r-jasppredictiveanalytics/PKGBUILD, BioArchLinux/r-jasppredictiveanalytics/lilac.yaml, BioArchLinux/r-scoringutils/PKGBUILD, BioArchLinux/r-scoringutils/lilac.py, BioArchLinux/r-scoringutils/lilac.yaml
- jasppredictiveanalytics
Close #
=> r-jasppredictiveanalytics: fix missing dependencies

BioArchLinux/r-scoringutils/PKGBUILD, BioArchLinux/r-scoringutils/lilac.yaml
=> r-scoringutils: fix build

BioArchLinux/r-metrics/PKGBUILD, BioArchLinux/r-metrics/lilac.py, BioArchLinux/r-metrics/lilac.yaml
- metrics
to fix depends of `r-scoringutils`
=> r-metrics: add new pkg to fix depends

BioArchLinux/r-semsens/PKGBUILD, BioArchLinux/r-semsens/lilac.yaml
=> r-semsens: fix pkg name

BioArchLinux/r-semsens/PKGBUILD, BioArchLinux/r-semsens/lilac.yaml
=> r-semsens: remove unnecessary dependencies

BioArchLinux/r-mirt/PKGBUILD, BioArchLinux/r-mirt/lilac.py, BioArchLinux/r-mirt/lilac.yaml, BioArchLinux/r-simdesign/PKGBUILD, BioArchLinux/r-simdesign/lilac.py, BioArchLinux/r-simdesign/lilac.yaml
=> r-mirt: add missing dependencies

BioArchLinux/r-simdesign/PKGBUILD, BioArchLinux/r-simdesign/lilac.yaml
=> r-simdesign: fix pkg dependencies

BioArchLinux/r-audio/PKGBUILD, BioArchLinux/r-audio/lilac.py, BioArchLinux/r-audio/lilac.yaml, BioArchLinux/r-beepr/PKGBUILD, BioArchLinux/r-beepr/lilac.py, BioArchLinux/r-beepr/lilac.yaml, BioArchLinux/r-rpushbullet/PKGBUILD, BioArchLinux/r-rpushbullet/lilac.py, BioArchLinux/r-rpushbullet/lilac.yaml
=> pkg: add missing dependencies

BioArchLinux/r-kernsmooth/PKGBUILD, BioArchLinux/r-kernsmooth/lilac.py, BioArchLinux/r-kernsmooth/lilac.yaml, BioArchLinux/r-lattice/PKGBUILD, BioArchLinux/r-mass/PKGBUILD, BioArchLinux/r-mass/lilac.py, BioArchLinux/r-mass/lilac.yaml
=> r-lattice: add missing depends

BioArchLinux/r-bfpack/PKGBUILD, BioArchLinux/r-bfpack/lilac.py, BioArchLinux/r-bfpack/lilac.yaml
- r-bfpack
Which was required by jaspBfpack
=> r-bfpack: add new pkg

BioArchLinux/r-rle/PKGBUILD, BioArchLinux/r-rle/lilac.py, BioArchLinux/r-rle/lilac.yaml
=> r-rle: add new pkg

BioArchLinux/r-bergm/PKGBUILD, BioArchLinux/r-bergm/lilac.yaml
=> r-bergm: fix depends

BioArchLinux/r-bergm/PKGBUILD, BioArchLinux/r-bergm/lilac.yaml, BioArchLinux/r-rglpk/PKGBUILD, BioArchLinux/r-rglpk/lilac.py, BioArchLinux/r-rglpk/lilac.yaml
=> r-rglpk: add new pkgs

BioArchLinux/snapgene/PKGBUILD, BioArchLinux/snapgene/lilac.yaml, BioArchLinux/snapgene/snapgene.sh
- snapgene
add new pkg
Close #
=> snapgene: add new pkg

BioArchLinux/spades/PKGBUILD
=> fix spades-4.2.0 build
