BioArchLinux/Packages

- BioArchLinux/r-metabma/PKGBUILD
- BioArchLinux/r-metabma/lilac.py
- BioArchLinux/r-metabma/lilac.yaml
- r-rstanarm, r-metabma
Close #54
`make` is exported as `make -j5` which uses no more than 10GiB memory. It should be safe now.
> retrict cpu and ram usage

- BioArchLinux/r-frf2/PKGBUILD
- BioArchLinux/r-openmx/PKGBUILD
- r-frf2, r-openmx
None.
openmx uses too much CPU power, it is now restricted to 5 threads.
frf2 has no license bundled.
> Fix frf2 and optimze openmx

- BioArchLinux/python-grid-strategy/PKGBUILD
- BioArchLinux/python-grid-strategy/lilac.yaml
- BioArchLinux/python-oldest-supported-numpy/PKGBUILD
- BioArchLinux/python-oldest-supported-numpy/lilac.yaml
- BioArchLinux/python-pairwisedist/PKGBUILD
- BioArchLinux/python-pairwisedist/lilac.yaml
- BioArchLinux/python-scikit-learn-extra/PKGBUILD
- BioArchLinux/python-scikit-learn-extra/lilac.yaml
- BioArchLinux/python-upsetplot/PKGBUILD
- BioArchLinux/python-upsetplot/lilac.yaml
- python-scikit-learn-extra
- python-oldest-supported-numpy
- python-pairwisedist
- python-grid-strategy
- python-upsetplot
- Close #110
- apart from aforementioned issue this pull request also adds some more dependencies mentioned in issue #107
> Add python-scikit-learn-extra & some more deps for #107

- BioArchLinux/bustools/PKGBUILD
- BioArchLinux/bustools/lilac.yaml
- BioArchLinux/kallisto/PKGBUILD
- BioArchLinux/kallisto/lilac.yaml
- BioArchLinux/python-hdbscan/PKGBUILD
- BioArchLinux/python-hdbscan/lilac.yaml
- BioArchLinux/python-matplotlib-venn/PKGBUILD
- BioArchLinux/python-matplotlib-venn/lilac.yaml
- BioArchLinux/python-numba/PKGBUILD
- BioArchLinux/python-numba/lilac.yaml
- kallisto
- python-numba
- python-hdbscan
- python-matplotlib-venn
- bustools (optional dependency for kallisto)
Additional dependencies for #107 imported from AUR
All the PKGUILDS except for bustools have been imported on as is basis from AUR wherever possible with as little modification as possible.
> Adding dependencies for RNAlysis from AUR

- BioArchLinux/diamond/PKGBUILD
- diamond
Close # NA
According to the [wiki ](https://github.com/bbuchfink/diamond/wiki/2.-Installation#blast-database-support)from upstream support for working with BLAST databases is not enabled by default when compiling from sources. the revised `PKGBUILD` enables the support for BLAST as per instructions from wiki.
> diamond: enable support for using BLAST databases

- BioArchLinux/salmon/PKGBUILD
- salmon
this pull request updates 'PKGBUILD' to be inline with arch guidelines as much as possible. 
running `namcap` on previous salmon package results in following output
```bash
salmon E: Insecure RUNPATH '$ORIGIN/../../lib' in file ('usr/bin/salmon')
salmon W: Dependency bzip2 included but already satisfied
```
package built using revised PKGBUILD produces a clean `namcap` outpu without any of aforementioned errors. 
The `PKGBUILD` has also been updated to run bundled tests provided by upstream as part of build process.
> salmon: fix cmake flags inline with Archwiki instructions

- BioArchLinux/r-sf/lilac.yaml
- r-sf
r-sf 1.0.12-2 on the bioarchlinux repo depends on `libgdal.so.32`, but the official Arch `gdal` package was updated a few days ago to provide `libgdal.so.33`.
This pr triggers a rebuild with lilac.
After the Arch bug [78547](https://bugs.archlinux.org/task/78547) has been fixed, rebuilds can be automated by adding
```yaml
- source: alpm
alpm: gdal
repo: community
provided: libgdal.so
```
to the `update_on` section in `lilac.yaml`.
> r-sf: rebuild with libgdal.so.33

- BioArchLinux/r-exact2x2/PKGBUILD
- BioArchLinux/r-exact2x2/lilac.yaml
- BioArchLinux/r-exactci/PKGBUILD
- BioArchLinux/r-exactci/lilac.yaml
- BioArchLinux/r-mvnormtest/PKGBUILD
- BioArchLinux/r-mvnormtest/lilac.yaml
- BioArchLinux/r-pmcmr/PKGBUILD
- BioArchLinux/r-pmcmr/lilac.yaml
- BioArchLinux/r-regsem/PKGBUILD
- BioArchLinux/r-regsem/lilac.yaml
- BioArchLinux/r-rprotobuf/PKGBUILD
- BioArchLinux/r-rprotobuf/lilac.yaml
- BioArchLinux/r-ssanv/PKGBUILD
- BioArchLinux/r-ssanv/lilac.yaml
add r-pkgs depended by jamovi
using cran2pkgbuild.py
Close #
> jamovi*: add r-pkgs depends

- BioArchLinux/python-pyexcel-ezodf/PKGBUILD
- BioArchLinux/python-pyexcel-ezodf/lilac.yaml
add python-pyexcel-ezodf as dependence for jamovi
- python-pyexcel-ezodf
Close #
> python-pyexcel-ezodf: init

- BioArchLinux/python-orange3/PKGBUILD
- BioArchLinux/python-orange3/lilac.yaml
- python-orange3
fix the denpendence from python-pyyaml to python-yaml
the pypi pkg named pyyaml so the script auto write 'python-pyyaml'  but in extra it's 'python-yaml'
> python-orange3: Fix dependence

- BioArchLinux/fastqc/PKGBUILD
- BioArchLinux/fastqc/fastqc.sh
- fastqc
Close #130
@mmahmoudian
As said in the bug report, `fastqc` fails to build in a non-chroot environment, if the default java version (as set by `archlinux-java`) is older than 11. In addition to that, the application fails to launch if the default java is older than 11. This bug is not Manjaro specific, as it has been tested on Arch.
This patch makes the package use the latest available java version during build. The make dependency `java-environment>=11` guarantees that a recent one is available. During application startup the latest available java is chosen as well, if the default java is too old.
> fastqc: fix build and startup when default java is too old

- BioArchLinux/canu/PKGBUILD
- BioArchLinux/canu/canu_version.patch
- BioArchLinux/canu/external-mhap.patch
- BioArchLinux/canu/lilac.yaml
- BioArchLinux/canu/use-arch-mhap-at-runtime.patch
- canu
mhap aligner has been packaged as per arch guidlines and has been added to the repo. This PR adds patches so that canu uses repo packaged 'mhap.jar' instead of bundled precompiled jar
> canu: use external mhap packaged in repo

- BioArchLinux/alevin-fry/PKGBUILD
- BioArchLinux/alevin-fry/lilac.yaml
Disables lto on vendored mimalloc compilation.
Setting `lto = "off"` in `Cargo.toml` most likely only affects the rust compilation, but not the C compilation of mimalloc. The `lto` PKGBUILD option adds the `-flto` flag to `CFLAGS`, so it needs to be disabled. The lto used by the rust compiler isn't a problem.
> alevin-fry: fix build

- BioArchLinux/tcoffee/lilac.yaml
- tcoffee
lilac can't get right newest-tags because bad tags-writting, i change to regex
[tags here](https://github.com/cbcrg/tcoffee/tags)
> tcoffee: fix lilac.yaml

- BioArchLinux/veusz/lilac.yaml
-  veusz
- fix lilac
Before:
use_max_tag got two(need 3.6.2) :
```
'update_info': [['3.6.2', 'veusz3d-2.1.101']]
```
err:
```
==> ERROR: pkgver is not allowed to contain colons, forward slashes, hyphens or whitespace.
```
Fixed:
```
use_latest_release
```
> veusz: fix lilac.yaml

- BioArchLinux/jasp-desktop/lilac.yaml
- BioArchLinux/r-jasprobustttests/PKGBUILD
- BioArchLinux/r-jasprobustttests/lilac.yaml
- jaspRobustTTests 
N/A
This is a new modules for jaspDesktop package, I just added it according to the fixed format, not tested.
request a review from @sukanka with thanks.
Another suggestion: If the build system is able to read the submodule from the main repository for example (a [.gitmodules](https://github.com/jasp-stats/jasp-desktop/blob/stable/.gitmodules) file from [JASP repo](https://github.com/jasp-stats/jasp-desktop/tree/stable/Modules) ), without any tag tracking and manual addition, the build system is always able to read the HEAD of the current reference of the git submodule.As such, this will also available for any git repository with submodules:-)
great job BioArchLinux team!
> Add jaspRobustTTests module

- BioArchLinux/snpeff/lilac.py
- BioArchLinux/snpeff/lilac.yaml
This fetches the SnpSift version using nvchecker. The benefit of this is simpler code, and also lilac will rebuild the package when SnpSift is updated.
Some other notes:
- If both `pre_build` function in `lilac.py` and a `pre_build_script` in `lilac.yaml` are defined, only one of them is run. I think only the `pre_build_script` is effective in this case.
- `update_pkgver_and_pkgrel` runs `updpkgsums` automatically.
- `.lstrip('v')` is unnecessary for the `update_pkgver_and_pkgrel` call, because the `prefix: v` nvchecker option already strips the `v` prefix.
- Comparing the version tags as strings doesn't work. For example, `"10.1" < "5.1"` is `True` in python. It's better to let nvchecker decide what is the max tag.
> snpeff: use update_on to get SnpSift version

- BioArchLinux/minimap2/PKGBUILD
- BioArchLinux/minimap2/hardening.patch
- BioArchLinux/minimap2/lilac.yaml
- minimap2
NA
1. build all the binaries as included in Makefile
2. Binaries are hardened with recommended build flags as per archlinux wiki
3. included library files in the package archive so that same can be used for building other packages
4. include manpages and test files from upstream into package archive
> minimap2: harden binaries and add libs to package

- README.md
Fix the BioArchLinux setup instructions in README.md to not cause partial upgrades.
On Arch Linux, [partial upgrades are unsupported](https://wiki.archlinux.org/title/System_maintenance#Partial_upgrades_are_unsupported) and can break the system. Specifically, running `pacman -Sy` without the `u` option can lead to a partial upgrade, if new packages are installed afterwards without running `pacman -Su`. To prevent this, change the instructions to do `-Syu` instead.
This also removes the second `y` option, since it's unnecessary and wastes mirror bandwidth. Pacman can automatically figure out which databases need to be downloaded.
> Fix usage instructions to prevent partial upgrades

- BioArchLinux/python-pyfastani/PKGBUILD
- `python-pyfastani`
`fastani` is listed as a dependency of `python-pyfastani`, but the Python package comes batteries-included and doesn't require the original FastANI binary.
> python-pyfastani: remove `fastani` from `depends`

- BioArchLinux/python-pyhmmer/PKGBUILD
- BioArchLinux/python-pyhmmer/lilac.yaml
- `python-pyhmmer`
N/A
This PR adds a package for `python-pyhmmer` using the PKGBUILD I wrote for the AUR.
> python-pyhmmer: add package

- BioArchLinux/tbtools/PKGBUILD
new entry name "tbtools" may be better, especially works well in kde/gnome's search bar
Close #
> tbtools: fix entry name

- BioArchLinux/tbtools/PKGBUILD
I tried jre(8,11,17,21,22) only jre8 can't run.
So update to jre>=11
- tbtools
Close #
> tbtools: update jre(>=11)

- BioArchLinux/imagej2/lilac.yaml
AUR's imagej2 was adopted by kiri
- imagej2
add support for AUR
> imagej2: add aur support

- BioArchLinux/imagej2/PKGBUILD
- imagej2
Close #219 
binary wrapper generated with updated PKGBUILD is able to launch the application both from GUI shortcut as well as console.
> imagej2: fix binary wrapper generation

- BioArchLinux/jasp-desktop/PKGBUILD
- BioArchLinux/jasp-desktop/lilac.yaml
- BioArchLinux/r-bff/PKGBUILD
- BioArchLinux/r-bff/lilac.py
- BioArchLinux/r-bff/lilac.yaml
- BioArchLinux/r-jaspbff/PKGBUILD
- BioArchLinux/r-jaspbff/lilac.py
- BioArchLinux/r-jaspbff/lilac.yaml
- BioArchLinux/r-jaspbfpack/PKGBUILD
- BioArchLinux/r-jaspbfpack/lilac.py
- BioArchLinux/r-jaspbfpack/lilac.yaml
- jasp-desktop
Close #
cc @sukanka I don't have an Arch environment so I didn't test on local. dont know why I also cannot open build logs in https://build.bioarchlinux.org/ , seems it was shutdown.
> jasp-desktop: add new modules for JASP

- BioArchLinux/r-jaspmachinelearning/lilac.yaml
> jaspmachinelearning: fix pkg r depends

- BioArchLinux/r-ggsurvfit/PKGBUILD
- BioArchLinux/r-ggsurvfit/lilac.yaml
>  r-ggsurvfit: remove dependence of r-survival

- BioArchLinux/python-pyhmmer/PKGBUILD
- python-pyhmmer
This PR updates the `python-pyhmmer` PKGBUILD to the latest version. The last release (`v0.11.0`) changed the build system from `setuptools` to CMake and `scikit-build-core`, so the build dependencies and process had to be updated.
> python-pyhmmer: Update `python-pyhmmer` PKGBUILD

- BioArchLinux/canu/PKGBUILD
- BioArchLinux/canu/external-mhap.patch
- BioArchLinux/canu/lilac.yaml
- BioArchLinux/canu/use-arch-mhap-at-runtime.patch
- canu
Close NA
1. undo changes made in commit [here](https://github.com/BioArchLinux/Packages/commit/e7c8b88b8a641b8475331c6925eed8da939008ef) and restores patches so that `canu` will use `mhap` provided by the repo
2. fixes licenses array
> canu: restore patches to use dependencies from repo

- BioArchLinux/strobealign/PKGBUILD
- BioArchLinux/strobealign/lilac.yaml
This PR adds [`strobealign`](https://github.com/ksahlin/strobealign), another read aligner with very high performance. 
It builds inside the bioarchlinux/bioarchlinux Docker image with the dependencies and `base-devel` installed.
- `strobealign`
N/A
> strobealign: adding version 0.16.0

- BioArchLinux/alevin-fry/PKGBUILD
- BioArchLinux/chopper/PKGBUILD
- BioArchLinux/cramino/PKGBUILD
From https://wiki.archlinux.org/title/Rust_package_guidelines#Prepare
This allows other architectures to fetch sources with cargo without a patch.
See https://gitlab.archlinux.org/groups/archlinux/packaging/-/epics/1
- alevin-fry
- chopper
- cramino
> alevin-fry,chopper,cramino: get cargo fetch more generically

- BioArchLinux/calamares/PKGBUILD
- Calamares
This pull request is being submitted based on the related issue: #270 
Inside the ```build()``` function of the ```PKGBUILD```, ```skip_modules()``` has been changed to include all the packages. In addition, as discussed in issue #270 , ```plasma-framework5``` has been removed. Nonetheless, ```mkinitcpio```, which is one of the dependencies of Calamares, has been added.
> calamares: Update Calamares' PKGBUILD

- BioArchLinux/snapgene-viewer/lilac.yaml
- snapgene-viewer
Current version 7.2.1is the last version for snapgene-viewer as an independent package.
https://www.snapgene.com/snapgene-viewer: "SnapGene and SnapGene Viewer have been combined into a single SnapGene application. 
The new snapgene in Viewer Mod will show an ad banner in the bottom when open it, and need to close manually every time. So i decided to keep the snapgene-viewer and lock in 7.2.1 version.
Close #
> snapgene-viewer: change to manually update

- BioArchLinux/cd-hit/PKGBUILD
- BioArchLinux/cd-hit/lilac.yaml
- cd-hit
add new pkg
CD-HIT is a very widely used program for clustering and comparing protein or nucleotide sequences.
> cd-hit: add new pkg
